services:
  postgres:
    image: postgres:16-alpine
    container_name: boardgamehub-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BoardGameHub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d BoardGameHub" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: boardgamehub-pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: boardgamehub-backend
  #   ports:
  #     - "5109:8080"
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Database=BoardGameHub;Username=postgres;Password=password
  #     - Jwt__Key=YourSuperSecretKeyGoesHereForLocalDev
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: boardgamehub-frontend
  #   ports:
  #     - "4200:8080"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
  pgadmin_data:
