sonar.projectKey=higherkey_board-game-hub
sonar.organization=higherkey

# Project display info
sonar.projectName=Board Game Hub
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=backend/BoardGameHub.Api,frontend/src
sonar.exclusions=**/node_modules/**,**/obj/**,**/bin/**,**/*.spec.ts,backend/BoardGameHub.Tests/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Backend Coverage (OpenCover)
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

# Frontend Coverage (LCOV)
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
