// <auto-generated />
using System;
using BoardGameHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251226002557_AddGameAttributes")]
    partial class AddGameAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameHub.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AveragePlayTime")
                        .HasColumnType("integer");

                    b.Property<string>("CodeKey")
                        .HasColumnType("text");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "Scatterbrain",
                            AveragePlayTime = 15,
                            Complexity = 1,
                            Description = "The classic party game. Come up with unique answers for categories for a chosen letter.",
                            Icon = "🧠",
                            MaxPlayers = 10,
                            MinPlayers = 2,
                            Name = "Scatterbrain",
                            Status = 0,
                            Tags = "Word,Party,Timed"
                        },
                        new
                        {
                            Id = "Babble",
                            AveragePlayTime = 10,
                            Complexity = 2,
                            Description = "Find as many words as you can in the grid of letters before time runs out!",
                            Icon = "🔤",
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Babble",
                            Status = 0,
                            Tags = "Word,Puzzle,Timed"
                        },
                        new
                        {
                            Id = "OneAndOnly",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            Description = "Work together to guess the mystery word by writing unique one-word clues.",
                            Icon = "🃏",
                            MaxPlayers = 7,
                            MinPlayers = 3,
                            Name = "One & Only",
                            Status = 0,
                            Tags = "Cooperative,Word,Social"
                        },
                        new
                        {
                            Id = "NomDeCode",
                            AveragePlayTime = 25,
                            Complexity = 2,
                            Description = "Give one-word clues to help your team guess their agents.",
                            Icon = "🕵️‍♀️",
                            MaxPlayers = 8,
                            MinPlayers = 4,
                            Name = "Nom de Code",
                            Status = 2,
                            Tags = "Teams,Word,Social"
                        },
                        new
                        {
                            Id = "Warships",
                            AveragePlayTime = 15,
                            Complexity = 2,
                            Description = "Sink your opponent's fleet before they sink yours.",
                            Icon = "🚢",
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Warships",
                            Status = 2,
                            Tags = "Strategy,Combat"
                        },
                        new
                        {
                            Id = "FourInARow",
                            AveragePlayTime = 5,
                            Complexity = 1,
                            Description = "Connect four of your checkers in a row.",
                            Icon = "🔴",
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Four in a Row",
                            Status = 2,
                            Tags = "Strategy,Puzzle"
                        },
                        new
                        {
                            Id = "Checkers",
                            AveragePlayTime = 15,
                            Complexity = 2,
                            Description = "Jump over opponent pieces to capture them.",
                            Icon = "🏁",
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Checkers",
                            Status = 2,
                            Tags = "Strategy,Classic"
                        },
                        new
                        {
                            Id = "UniversalTranslator",
                            AveragePlayTime = 45,
                            Complexity = 3,
                            Description = "Communication game with a hidden traitor.",
                            Icon = "👽",
                            MaxPlayers = 8,
                            MinPlayers = 4,
                            Name = "Universal Translator",
                            Status = 0,
                            Tags = "Social Deduction,Sci-Fi,Bluffing"
                        },
                        new
                        {
                            Id = "Pictophone",
                            AveragePlayTime = 30,
                            Complexity = 1,
                            Description = "Telephone with drawings.",
                            Icon = "🎨",
                            MaxPlayers = 12,
                            MinPlayers = 4,
                            Name = "Pictophone",
                            Status = 0,
                            Tags = "Drawing,Party,Humor"
                        },
                        new
                        {
                            Id = "Wisecrack",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            Description = "Answer simple prompts with witty answers.",
                            Icon = "💬",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Wisecrack",
                            Status = 0,
                            Tags = "Humor,Social,Party"
                        },
                        new
                        {
                            Id = "Poppycock",
                            AveragePlayTime = 30,
                            Complexity = 2,
                            Description = "Bluff your friends with fake definitions.",
                            Icon = "🤥",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Poppycock",
                            Status = 0,
                            Tags = "Bluffing,Word,Social"
                        },
                        new
                        {
                            Id = "Symbology",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            Description = "Communicate ideas using universal icons.",
                            Icon = "💡",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Symbology",
                            Status = 0,
                            Tags = "Cooperative,Communication,Icons"
                        },
                        new
                        {
                            Id = "BreakingNews",
                            AveragePlayTime = 15,
                            Complexity = 1,
                            Description = "Frantic teleprompter fun where writers sabotage the anchor.",
                            Icon = "📰",
                            MaxPlayers = 10,
                            MinPlayers = 3,
                            Name = "Breaking News",
                            Status = 0,
                            Tags = "Humor,Social,Party,Timed"
                        },
                        new
                        {
                            Id = "Deepfake",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            Description = "A generative AI tries to blend in with human artists.",
                            Icon = "🤖",
                            MaxPlayers = 10,
                            MinPlayers = 4,
                            Name = "Deepfake",
                            Status = 0,
                            Tags = "Social Deduction,Drawing,AI"
                        },
                        new
                        {
                            Id = "SushiTrain",
                            AveragePlayTime = 25,
                            Complexity = 2,
                            Description = "Draft the best meal from the passing conveyor belt!",
                            Icon = "🍣",
                            MaxPlayers = 5,
                            MinPlayers = 2,
                            Name = "Sushi Train!",
                            Status = 0,
                            Tags = "Drafting,Card Game,Family"
                        },
                        new
                        {
                            Id = "GreatMinds",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            Description = "Synchronize your minds and play cards in ascending order without speaking!",
                            Icon = "🌟",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            Name = "Great Minds",
                            Status = 0,
                            Tags = "Cooperative,Card Game,Social"
                        });
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSessionPlayer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessionPlayers");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.ChatMessage", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BoardGameHub.Api.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.Friendship", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSessionPlayer", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSession", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
