// <auto-generated />
using System;
using BoardGameHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304155016_ForceRefreshEmojis")]
    partial class ForceRefreshEmojis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameHub.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AveragePlayTime")
                        .HasColumnType("integer");

                    b.Property<string>("CodeKey")
                        .HasColumnType("text");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRoundLengthSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingsMetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "Scatterbrain",
                            AveragePlayTime = 15,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 180,
                            Description = "The classic party game. Come up with unique answers for categories for a chosen letter.",
                            Icon = "🧠",
                            MaxPlayers = 10,
                            MinPlayers = 2,
                            Name = "Scatterbrain",
                            SettingsMetadataJson = "[{\"id\":\"letterMode\",\"label\":\"Letter Difficulty\",\"type\":\"select\",\"options\":[{\"label\":\"Normal (No Q, V,X, Z)\",\"value\":0},{\"label\":\"Hard (Only Q, V, X, Z...)\",\"value\":1},{\"label\":\"True Random\",\"value\":2}]}]",
                            Status = 2,
                            Tags = "Word,Party,Timed",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "Babble",
                            AveragePlayTime = 10,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 180,
                            Description = "Find as many words as you can in the grid of letters before time runs out!",
                            Icon = "🔤",
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Babble",
                            SettingsMetadataJson = "[{\"id\":\"boardSize\",\"label\":\"Board Size\",\"type\":\"select\",\"options\":[{\"label\":\"4x4 (Classic)\",\"value\":4},{\"label\":\"5x5 (Big Babble)\",\"value\":5},{\"label\":\"6x6 (Super Babble)\",\"value\":6}]}]",
                            Status = 1,
                            Tags = "Word,Puzzle,Timed",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "OneAndOnly",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Work together to guess the mystery word by writing unique one-word clues.",
                            Icon = "🃏",
                            MaxPlayers = 7,
                            MinPlayers = 3,
                            Name = "One & Only",
                            Status = 2,
                            Tags = "Cooperative,Word,Social",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "NomDeCode",
                            AveragePlayTime = 25,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Give one-word clues to help your team guess their agents.",
                            Icon = "🕵️‍♀️",
                            MaxPlayers = 8,
                            MinPlayers = 4,
                            Name = "Nom de Code",
                            Status = 2,
                            Tags = "Teams,Word,Social",
                            TimerType = 1
                        },
                        new
                        {
                            Id = "Warships",
                            AveragePlayTime = 15,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Sink your opponent's fleet before they sink yours.",
                            Icon = "🚢",
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Warships",
                            Status = 2,
                            Tags = "Strategy,Combat",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "FourInARow",
                            AveragePlayTime = 5,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Connect four of your checkers in a row.",
                            Icon = "🔴",
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Four in a Row",
                            Status = 2,
                            Tags = "Strategy,Puzzle",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "UniversalTranslator",
                            AveragePlayTime = 45,
                            Complexity = 3,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Communication game with a hidden traitor.",
                            Icon = "👽",
                            MaxPlayers = 8,
                            MinPlayers = 4,
                            Name = "Universal Translator",
                            Status = 2,
                            Tags = "Social Deduction,Sci-Fi,Bluffing",
                            TimerType = 1
                        },
                        new
                        {
                            Id = "Pictophone",
                            AveragePlayTime = 30,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 60,
                            Description = "Telephone with drawings.",
                            Icon = "🎨",
                            MaxPlayers = 12,
                            MinPlayers = 4,
                            Name = "Pictophone",
                            Status = 2,
                            Tags = "Drawing,Party,Humor",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "Wisecrack",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 90,
                            Description = "Answer simple prompts with witty answers.",
                            Icon = "💬",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Wisecrack",
                            Status = 2,
                            Tags = "Humor,Social,Party",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "Poppycock",
                            AveragePlayTime = 30,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Bluff your friends with fake definitions.",
                            Icon = "🤥",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Poppycock",
                            Status = 2,
                            Tags = "Bluffing,Word,Social",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Symbology",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Communicate ideas using universal icons.",
                            Icon = "💡",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Symbology",
                            Status = 2,
                            Tags = "Cooperative,Communication,Icons",
                            TimerType = 1
                        },
                        new
                        {
                            Id = "BreakingNews",
                            AveragePlayTime = 15,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 60,
                            Description = "Frantic teleprompter fun where writers sabotage the anchor.",
                            Icon = "📰",
                            MaxPlayers = 10,
                            MinPlayers = 3,
                            Name = "Breaking News",
                            Status = 2,
                            Tags = "Humor,Social,Party,Timed",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "Deepfake",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "A generative AI tries to blend in with human artists.",
                            Icon = "🤖",
                            MaxPlayers = 10,
                            MinPlayers = 4,
                            Name = "Deepfake",
                            Status = 2,
                            Tags = "Social Deduction,Drawing,AI",
                            TimerType = 1
                        },
                        new
                        {
                            Id = "SushiTrain",
                            AveragePlayTime = 25,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Draft the best meal from the passing conveyor belt!",
                            Icon = "🍣",
                            MaxPlayers = 5,
                            MinPlayers = 2,
                            Name = "Sushi Train!",
                            Status = 2,
                            Tags = "Drafting,Card Game,Family",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "GreatMinds",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Synchronize your minds and play cards in ascending order without speaking!",
                            Icon = "🌟",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            Name = "Great Minds",
                            Status = 2,
                            Tags = "Cooperative,Card Game,Social",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Farkle",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Push your luck with six dice to score 10,000 points!",
                            Icon = "🎲",
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Farkle",
                            Status = 3,
                            Tags = "Dice,Party,Luck",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Spectrum",
                            AveragePlayTime = 30,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Read your team's mind on a scale of polar opposites.",
                            Icon = "🌈",
                            MaxPlayers = 12,
                            MinPlayers = 2,
                            Name = "Spectrum",
                            Status = 3,
                            Tags = "Social,Party,Team",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Courtship",
                            AveragePlayTime = 20,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Get your love letter delivered while exposing your rivals.",
                            Icon = "💌",
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            Name = "Courtship",
                            Status = 3,
                            Tags = "Deduction,Cards,Risk",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "SilentHeist",
                            AveragePlayTime = 10,
                            Complexity = 3,
                            DefaultRoundLengthSeconds = 180,
                            Description = "Coordinate moves in silence to rob a secure facility.",
                            Icon = "🤫",
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Silent Heist",
                            Status = 3,
                            Tags = "Coop,Real-time,Puzzle",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "FoleyArtist",
                            AveragePlayTime = 20,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 60,
                            Description = "Make sound effects for silent clips and have your friends guess the scene.",
                            Icon = "🎤",
                            MaxPlayers = 8,
                            MinPlayers = 3,
                            Name = "Foley Artist",
                            Status = 3,
                            Tags = "Audio,Party,Creative",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "LostInTranslation",
                            AveragePlayTime = 15,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 60,
                            Description = "Identify famous phrases garbled by too many translations.",
                            Icon = "🗣️",
                            MaxPlayers = 12,
                            MinPlayers = 3,
                            Name = "Lost in Translation",
                            Status = 3,
                            Tags = "Word,Humor,Puzzle",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "CodeBreaker",
                            AveragePlayTime = 15,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Hack the system by deducing the secret color sequence.",
                            Icon = "🔐",
                            MaxPlayers = 6,
                            MinPlayers = 2,
                            Name = "Code Breaker",
                            Status = 3,
                            Tags = "Logic,Deduction,Puzzle",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Yacht",
                            AveragePlayTime = 30,
                            Complexity = 1,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Classic dice rolling strategy. Get five of a kind!",
                            Icon = "⛵",
                            MaxPlayers = 8,
                            MinPlayers = 1,
                            Name = "Yacht",
                            Status = 3,
                            Tags = "Dice,Strategy,Classic",
                            TimerType = 0
                        },
                        new
                        {
                            Id = "Terminal",
                            AveragePlayTime = 20,
                            Complexity = 3,
                            DefaultRoundLengthSeconds = 300,
                            Description = "One Hacker. Four Agents. Keep talking to survive the infiltration.",
                            Icon = "📟",
                            MaxPlayers = 5,
                            MinPlayers = 2,
                            Name = "Terminal",
                            Status = 3,
                            Tags = "Cooperative,Asymmetric,Real-Time",
                            TimerType = 2
                        },
                        new
                        {
                            Id = "CloverMinded",
                            AveragePlayTime = 25,
                            Complexity = 2,
                            DefaultRoundLengthSeconds = 0,
                            Description = "Work together to associate keywords on your clover board.",
                            Icon = "🍀",
                            MaxPlayers = 6,
                            MinPlayers = 3,
                            Name = "Clover-Minded",
                            Status = 3,
                            Tags = "Cooperative,Word,Party",
                            TimerType = 0
                        });
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSessionPlayer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessionPlayers");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.ChatMessage", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BoardGameHub.Api.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.Friendship", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSessionPlayer", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BoardGameHub.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardGameHub.Api.Models.GameSession", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
