export const SYMBOLOGY_ICONS = [
    { id: '1', icon: '😀', tags: ['happy', 'face', 'person'] },
    { id: '2', icon: '😢', tags: ['sad', 'face'] },
    { id: '3', icon: '😡', tags: ['angry', 'face'] },
    { id: '4', icon: '❤️', tags: ['love', 'heart'] },
    { id: '5', icon: '💔', tags: ['heartbreak'] },
    { id: '6', icon: '👀', tags: ['see', 'eyes', 'look'] },
    { id: '7', icon: '👂', tags: ['hear', 'ear'] },
    { id: '8', icon: '🗣️', tags: ['speak', 'talk'] },
    { id: '9', icon: '👃', tags: ['smell', 'nose'] },
    { id: '10', icon: '✋', tags: ['stop', 'hand'] },
    { id: '11', icon: '👍', tags: ['good', 'yes'] },
    { id: '12', icon: '👎', tags: ['bad', 'no'] },
    { id: '13', icon: '👊', tags: ['fight', 'power'] },
    { id: '14', icon: '👋', tags: ['hello', 'goodbye'] },
    { id: '15', icon: '👶', tags: ['baby', 'small'] },
    { id: '16', icon: '👨', tags: ['man'] },
    { id: '17', icon: '👩', tags: ['woman'] },
    { id: '18', icon: '👴', tags: ['old'] },
    { id: '19', icon: '👮', tags: ['police', 'law'] },
    { id: '20', icon: 'doctor', iconChar: '🩺', tags: ['doctor', 'health'] }, // Using Objects for some concepts
    { id: '21', icon: '🐱', tags: ['cat', 'animal'] },
    { id: '22', icon: '🐶', tags: ['dog', 'animal'] },
    { id: '23', icon: '🦁', tags: ['wild', 'danger'] },
    { id: '24', icon: '🌲', tags: ['tree', 'nature'] },
    { id: '25', icon: '💧', tags: ['water', 'liquid'] },
    { id: '26', icon: '🔥', tags: ['fire', 'hot'] },
    { id: '27', icon: '🌎', tags: ['world', 'earth'] },
    { id: '28', icon: '🌙', tags: ['night', 'moon'] },
    { id: '29', icon: '☀️', tags: ['sun', 'day', 'light'] },
    { id: '30', icon: '☁️', tags: ['cloud', 'soft'] },
    { id: '31', icon: '⚡', tags: ['power', 'fast', 'energy'] },
    { id: '32', icon: '❄️', tags: ['cold', 'ice'] },
    { id: '33', icon: '🏠', tags: ['house', 'home'] },
    { id: '34', icon: '🚗', tags: ['car', 'travel'] },
    { id: '35', icon: '✈️', tags: ['fly', 'air'] },
    { id: '36', icon: '🚢', tags: ['water', 'sea'] },
    { id: '37', icon: '🚲', tags: ['cycle'] },
    { id: '38', icon: '🛑', tags: ['stop', 'red'] },
    { id: '39', icon: '⚓', tags: ['anchor', 'heavy'] },
    { id: '40', icon: '🚀', tags: ['space', 'future'] },
    { id: '41', icon: '⌚', tags: ['time'] },
    { id: '42', icon: '📱', tags: ['phone', 'tech'] },
    { id: '43', icon: '💻', tags: ['computer', 'work'] },
    { id: '44', icon: '📷', tags: ['photo', 'picture'] },
    { id: '45', icon: '🔍', tags: ['search', 'investigate'] },
    { id: '46', icon: '💡', tags: ['idea', 'light'] },
    { id: '47', icon: '🔌', tags: ['power', 'electric'] },
    { id: '48', icon: '🔨', tags: ['build', 'tool'] },
    { id: '49', icon: '🔫', tags: ['weapon', 'fight'] },
    { id: '50', icon: '💰', tags: ['money', 'rich'] },
    { id: '51', icon: '💎', tags: ['value', 'jewelry'] },
    { id: '52', icon: '🖊️', tags: ['write'] },
    { id: '53', icon: '📖', tags: ['read', 'book'] },
    { id: '54', icon: '🎨', tags: ['art', 'color'] },
    { id: '55', icon: '🎵', tags: ['music', 'sound'] },
    { id: '56', icon: '⚽', tags: ['sport'] },
    { id: '57', icon: '🎮', tags: ['game', 'play'] },
    { id: '58', icon: '🎲', tags: ['random', 'chance'] },
    { id: '59', icon: '🍎', tags: ['food', 'fruit'] },
    { id: '60', icon: '🍔', tags: ['food', 'meat'] },
    { id: '61', icon: '🍺', tags: ['drink', 'alcohol'] },
    { id: '62', icon: '☕', tags: ['coffee', 'hot drink'] },
    { id: '63', icon: '🎂', tags: ['celebrate', 'sweet'] },
    { id: '64', icon: '🏥', tags: ['hospital', 'sick'] },
    { id: '65', icon: '⛪', tags: ['church', 'religion'] },
    { id: '66', icon: '🚽', tags: ['toilet', 'dirty'] },
    { id: '67', icon: '🚿', tags: ['clean', 'water'] },
    { id: '68', icon: '🛏️', tags: ['sleep', 'bed'] },
    { id: '69', icon: '🚪', tags: ['door', 'exit'] },
    { id: '70', icon: '🔑', tags: ['key', 'secret'] },
    { id: '71', icon: '📦', tags: ['box', 'container'] },
    { id: '72', icon: '🎁', tags: ['gift'] },
    { id: '73', icon: '🗑️', tags: ['trash'] },
    { id: '74', icon: '📄', tags: ['paper'] },
    { id: '75', icon: 'scissors', iconChar: '✂️', tags: ['cut'] },
    { id: '76', icon: '📏', tags: ['measure', 'straight'] },
    { id: '77', icon: '🏳️', tags: ['surrender', 'white'] },
    { id: '78', icon: '🏴', tags: ['black'] },
    { id: '79', icon: '🏁', tags: ['finish', 'race'] },
    { id: '80', icon: '🚩', tags: ['flag', 'location'] },
    { id: '81', icon: '🔴', tags: ['red', 'circle'] },
    { id: '82', icon: '🔵', tags: ['blue', 'circle'] },
    { id: '82b', icon: '🟢', tags: ['green', 'circle'] },
    { id: '83', icon: '🔺', tags: ['up'] },
    { id: '84', icon: '🔻', tags: ['down'] },
    { id: '85', icon: '❌', tags: ['cross', 'wrong'] },
    { id: '86', icon: '⭕', tags: ['circle', 'ring'] },
    { id: '87', icon: '❓', tags: ['question'] },
    { id: '88', icon: '❗', tags: ['exclamation', 'important'] },
    { id: '89', icon: '➕', tags: ['plus', 'add'] },
    { id: '90', icon: '➖', tags: ['minus', 'remove'] },
    { id: '91', icon: '➗', tags: ['divide'] },
    { id: '92', icon: '♾️', tags: ['forever', 'infinity'] },
    { id: '93', icon: '✝️', tags: ['cross'] },
    { id: '94', icon: '⚧️', tags: ['trans'] },
    { id: '95', icon: '⚤', tags: ['sex'] }, // Actually lets stick to standard emojis
    { id: '96', icon: '☮️', tags: ['peace'] },
    { id: '97', icon: '☯️', tags: ['yin yang'] },
    { id: '98', icon: '☢️', tags: ['nuclear', 'danger'] },
    { id: '99', icon: '☣️', tags: ['biohazard', 'toxic'] },
];
