CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "DisplayName" text NOT NULL,
        "AvatarUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "ChatMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SenderId" text NOT NULL,
        "ReceiverId" text,
        "Content" text NOT NULL,
        "SentAt" timestamp with time zone NOT NULL,
        "IsGlobal" boolean NOT NULL,
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_AspNetUsers_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ChatMessages_AspNetUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE TABLE "Friendships" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RequesterId" text NOT NULL,
        "AddresseeId" text NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Friendships" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Friendships_AspNetUsers_AddresseeId" FOREIGN KEY ("AddresseeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Friendships_AspNetUsers_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_ChatMessages_ReceiverId" ON "ChatMessages" ("ReceiverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_ChatMessages_SenderId" ON "ChatMessages" ("SenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_Friendships_AddresseeId" ON "Friendships" ("AddresseeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    CREATE INDEX "IX_Friendships_RequesterId" ON "Friendships" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210151009_InitialSocial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251210151009_InitialSocial', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    ALTER TABLE "ChatMessages" ADD "Timestamp" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    CREATE TABLE "GameSessions" (
        "Id" text NOT NULL,
        "RoomCode" text NOT NULL,
        "GameType" text NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "IsPublic" boolean NOT NULL,
        CONSTRAINT "PK_GameSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    CREATE TABLE "GameSessionPlayers" (
        "Id" text NOT NULL,
        "GameSessionId" text NOT NULL,
        "UserId" text,
        "DisplayName" text NOT NULL,
        "Score" integer NOT NULL,
        "Rank" integer NOT NULL,
        CONSTRAINT "PK_GameSessionPlayers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GameSessionPlayers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_GameSessionPlayers_GameSessions_GameSessionId" FOREIGN KEY ("GameSessionId") REFERENCES "GameSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    CREATE INDEX "IX_GameSessionPlayers_GameSessionId" ON "GameSessionPlayers" ("GameSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    CREATE INDEX "IX_GameSessionPlayers_UserId" ON "GameSessionPlayers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211050352_AddGameHistory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251211050352_AddGameHistory', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212040424_AddGamesTable') THEN
    CREATE TABLE "Games" (
        "Id" text NOT NULL,
        "Name" text NOT NULL,
        "Icon" text NOT NULL,
        "Description" text NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212040424_AddGamesTable') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Battleship', 'Sink your opponent''s fleet before they sink yours.', '🚢', 'Battleship', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Boggle', 'Find as many words as you can in the grid of letters before time runs out!', '🔤', 'Boggle', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Catan', 'Trade, build, and settle the island of Catan.', '🏰', 'Settlers of Catan', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Checkers', 'Jump over opponent pieces to capture them.', '🏁', 'Checkers', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Chess', 'Strategic board game played on a checkered board.', '♟️', 'Chess', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Codenames', 'Give one-word clues to help your team guess their agents.', '🕵️‍♀️', 'Codenames', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Connect4', 'Connect four of your checkers in a row.', '🔴', 'Connect 4', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('JustOne', 'Work together to guess the mystery word by writing unique one-word clues.', '🃏', 'Just One', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Monopoly', 'Buy, sell, and trade properties to win.', '🎩', 'Monopoly', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Pictionary', 'Draw and guess words with your friends.', '🎨', 'Pictionary', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Scatterbrain', 'The classic party game. Come up with unique answers for categories for a chosen letter.', '🧠', 'Scatterbrain', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Scrabble', 'Create words on the board using letter tiles.', '📝', 'Scrabble', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Spyfall', 'Find the spy among you before they figure out the location.', '🕵️', 'Spyfall', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('TicketToRide', 'Build train routes across the country.', '🚂', 'Ticket to Ride', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Uno', 'The classic card game of matching colors and numbers.', '🃏', 'Uno', 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212040424_AddGamesTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251212040424_AddGamesTable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Catan';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Chess';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Monopoly';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Pictionary';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Scrabble';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Spyfall';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'TicketToRide';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Uno';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('BreakingNews', 'Frantic teleprompter fun where writers sabotage the anchor.', '📰', 'Breaking News', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Pictophone', 'Draw, guess, and laugh as the message gets distorted.', '🖍️', 'Pictophone', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Poppycock', 'Bluff your friends with fake definitions.', '🤥', 'Poppycock', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Symbology', 'Communicate ideas using universal icons.', '💡', 'Symbology', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('UniversalTranslator', 'Decipher the alien message before ''J'' jams the signal.', '👽', 'Universal Translator', 2);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Wisecrack', 'Answer simple prompts with witty answers.', '💬', 'Wisecrack', 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213070646_RemoveBrandedGames') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251213070646_RemoveBrandedGames', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Boggle';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Status" = 0
    WHERE "Id" = 'BreakingNews';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Description" = 'Telephone with drawings.', "Icon" = '🎨', "Status" = 0
    WHERE "Id" = 'Pictophone';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Status" = 0
    WHERE "Id" = 'Poppycock';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Status" = 0
    WHERE "Id" = 'Symbology';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Description" = 'Communication game with a hidden traitor.', "Status" = 0
    WHERE "Id" = 'UniversalTranslator';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    UPDATE "Games" SET "Status" = 0
    WHERE "Id" = 'Wisecrack';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Deepfake', 'A generative AI tries to blend in with human artists.', '🤖', 'Deepfake', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('WordHunt', 'Find as many words as you can in the grid of letters before time runs out!', '🔤', 'Word Hunt', 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213162834_RenameBoggleToWordHunt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251213162834_RenameBoggleToWordHunt', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214010911_RenameBattleshipToWarships') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Battleship';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214010911_RenameBattleshipToWarships') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'WordHunt';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214010911_RenameBattleshipToWarships') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Babble', 'Find as many words as you can in the grid of letters before time runs out!', '🔤', 'Babble', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('GreatMinds', 'Synchronize your minds and play cards in ascending order without speaking!', '🧠', 'Great Minds', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('SushiTrain', 'Draft the best meal from the passing conveyor belt!', '🍣', 'Sushi Train!', 0);
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('Warships', 'Sink your opponent''s fleet before they sink yours.', '🚢', 'Warships', 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214010911_RenameBattleshipToWarships') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214010911_RenameBattleshipToWarships', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011022_RenameConnect4ToFourInARow') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Connect4';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011022_RenameConnect4ToFourInARow') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('FourInARow', 'Connect four of your checkers in a row.', '🔴', 'Four in a Row', 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011022_RenameConnect4ToFourInARow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214011022_RenameConnect4ToFourInARow', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011111_RenameCodenamesToNomDeCode') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'Codenames';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011111_RenameCodenamesToNomDeCode') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('NomDeCode', 'Give one-word clues to help your team guess their agents.', '🕵️‍♀️', 'Nom de Code', 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011111_RenameCodenamesToNomDeCode') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214011111_RenameCodenamesToNomDeCode', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011645_RenameJustOneToOneAndOnly') THEN
    DELETE FROM "Games"
    WHERE "Id" = 'JustOne';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011645_RenameJustOneToOneAndOnly') THEN
    INSERT INTO "Games" ("Id", "Description", "Icon", "Name", "Status")
    VALUES ('OneAndOnly', 'Work together to guess the mystery word by writing unique one-word clues.', '🃏', 'One & Only', 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214011645_RenameJustOneToOneAndOnly') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214011645_RenameJustOneToOneAndOnly', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214074751_RenameWordHuntToBabble') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214074751_RenameWordHuntToBabble', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "AveragePlayTime" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "CodeKey" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "Complexity" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "MaxPlayers" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "MinPlayers" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    ALTER TABLE "Games" ADD "Tags" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 10, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 8, "MinPlayers" = 1, "Tags" = 'Word,Puzzle,Timed'
    WHERE "Id" = 'Babble';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 15, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 10, "MinPlayers" = 3, "Tags" = 'Humor,Social,Party,Timed'
    WHERE "Id" = 'BreakingNews';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 15, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 2, "MinPlayers" = 2, "Tags" = 'Strategy,Classic'
    WHERE "Id" = 'Checkers';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 20, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 10, "MinPlayers" = 4, "Tags" = 'Social Deduction,Drawing,AI'
    WHERE "Id" = 'Deepfake';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 5, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 2, "MinPlayers" = 2, "Tags" = 'Strategy,Puzzle'
    WHERE "Id" = 'FourInARow';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 20, "CodeKey" = NULL, "Complexity" = 2, "Icon" = '🌟', "MaxPlayers" = 4, "MinPlayers" = 2, "Tags" = 'Cooperative,Card Game,Social'
    WHERE "Id" = 'GreatMinds';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 25, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 8, "MinPlayers" = 4, "Tags" = 'Teams,Word,Social'
    WHERE "Id" = 'NomDeCode';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 20, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 7, "MinPlayers" = 3, "Tags" = 'Cooperative,Word,Social'
    WHERE "Id" = 'OneAndOnly';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 30, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 12, "MinPlayers" = 4, "Tags" = 'Drawing,Party,Humor'
    WHERE "Id" = 'Pictophone';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 30, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 8, "MinPlayers" = 3, "Tags" = 'Bluffing,Word,Social'
    WHERE "Id" = 'Poppycock';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 15, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 10, "MinPlayers" = 2, "Tags" = 'Word,Party,Timed'
    WHERE "Id" = 'Scatterbrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 25, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 5, "MinPlayers" = 2, "Tags" = 'Drafting,Card Game,Family'
    WHERE "Id" = 'SushiTrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 20, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 8, "MinPlayers" = 3, "Tags" = 'Cooperative,Communication,Icons'
    WHERE "Id" = 'Symbology';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 45, "CodeKey" = NULL, "Complexity" = 3, "MaxPlayers" = 8, "MinPlayers" = 4, "Tags" = 'Social Deduction,Sci-Fi,Bluffing'
    WHERE "Id" = 'UniversalTranslator';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 15, "CodeKey" = NULL, "Complexity" = 2, "MaxPlayers" = 2, "MinPlayers" = 2, "Tags" = 'Strategy,Combat'
    WHERE "Id" = 'Warships';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    UPDATE "Games" SET "AveragePlayTime" = 20, "CodeKey" = NULL, "Complexity" = 1, "MaxPlayers" = 8, "MinPlayers" = 3, "Tags" = 'Humor,Social,Party'
    WHERE "Id" = 'Wisecrack';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226002557_AddGameAttributes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251226002557_AddGameAttributes', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    ALTER TABLE "Games" ADD "DefaultRoundLengthSeconds" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    ALTER TABLE "Games" ADD "TimerType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 180, "Status" = 1, "TimerType" = 2
    WHERE "Id" = 'Babble';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 60, "Status" = 1, "TimerType" = 2
    WHERE "Id" = 'BreakingNews';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "TimerType" = 0
    WHERE "Id" = 'Checkers';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 1
    WHERE "Id" = 'Deepfake';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "TimerType" = 0
    WHERE "Id" = 'FourInARow';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 0
    WHERE "Id" = 'GreatMinds';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "TimerType" = 1
    WHERE "Id" = 'NomDeCode';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 0
    WHERE "Id" = 'OneAndOnly';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 60, "Status" = 1, "TimerType" = 2
    WHERE "Id" = 'Pictophone';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 0
    WHERE "Id" = 'Poppycock';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 180, "Status" = 1, "TimerType" = 2
    WHERE "Id" = 'Scatterbrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 0
    WHERE "Id" = 'SushiTrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 1
    WHERE "Id" = 'Symbology';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "Status" = 1, "TimerType" = 1
    WHERE "Id" = 'UniversalTranslator';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 0, "TimerType" = 0
    WHERE "Id" = 'Warships';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    UPDATE "Games" SET "DefaultRoundLengthSeconds" = 90, "Status" = 1, "TimerType" = 2
    WHERE "Id" = 'Wisecrack';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103050101_AddTimerSettingsToGameDefinition') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260103050101_AddTimerSettingsToGameDefinition', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    ALTER TABLE "Games" ADD "SettingsMetadataJson" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = '[{"id":"boardSize","label":"Board Size","type":"select","options":[{"label":"4x4 (Classic)","value":4},{"label":"5x5 (Big Babble)","value":5},{"label":"6x6 (Super Babble)","value":6}]}]'
    WHERE "Id" = 'Babble';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'BreakingNews';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Checkers';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Deepfake';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'FourInARow';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'GreatMinds';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'NomDeCode';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'OneAndOnly';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Pictophone';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Poppycock';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = '[{"id":"letterMode","label":"Letter Difficulty","type":"select","options":[{"label":"Normal (No Q, V,X, Z)","value":0},{"label":"Hard (Only Q, V, X, Z...)","value":1},{"label":"True Random","value":2}]}]'
    WHERE "Id" = 'Scatterbrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'SushiTrain';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Symbology';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'UniversalTranslator';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Warships';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    UPDATE "Games" SET "SettingsMetadataJson" = NULL
    WHERE "Id" = 'Wisecrack';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260103222036_AddSettingsMetadataToGameDefinition') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260103222036_AddSettingsMetadataToGameDefinition', '8.0.0');
    END IF;
END $EF$;
COMMIT;

