name: SonarQube Analysis

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET Dependencies
        run: dotnet restore backend/BoardGameHub.sln

      - name: Backend Tests & Coverage
        run: |
          dotnet test backend/BoardGameHub.Tests/BoardGameHub.Tests.csproj \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=../../coverage.opencover.xml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend Install
        run: npm --prefix frontend install

      - name: Frontend Tests & Coverage
        run: |
          npm --prefix frontend test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadless

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=higherkey_board-game-hub
            -Dsonar.organization=higherkey
            -Dsonar.sources=backend/BoardGameHub.Api,frontend/src
            -Dsonar.exclusions=**/node_modules/**,**/obj/**,**/bin/**,**/*.spec.ts,backend/BoardGameHub.Tests/**
            -Dsonar.cpd.ts.minimumLines=20
            -Dsonar.cpd.cs.minimumLines=20
            -Dsonar.cs.opencover.reportsPaths=coverage.opencover.xml
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



